### PR TITLE
`azuread_users` - Support nonunique mail nicknames

### LINKED ISSUE #1758: Support querying AzureAD users with non-unique mailNickname attribute
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The customer is using the Terraform’s AzureAD provider to fetch Users eligible for accessing their HashiCorp Vault instance and to perform Vault onboarding. In order to do this, they using a list of user emails from mail nicknames to fetch the User Principal Name (UPN). Currently, they have a blocker when they are onboarding where one of their users got another object within EntraID that uses the same mail nickname, receiving the following error: “More than one user found with email alias”.

While Azure best practices in many Active Directory situations is to use unique mail nicknames, this is not mandatory. The only attribute in Microsoft’s documentation that has to be unique is the UPN as it is used as the designated unique identifier for the EntraID object. The customer is facing a situation where in their instance, having duplicate `mailNickname` attributes is typical due to the fact that they are trying to onboard teams through GitLab groups where they need to be able to query with this specific attribute. This specific setup means that they will be querying users with duplicate `mailNickName`s as identifiers, and this not only intentional, but technically allowed due to the fact that `mailNickName` is not inherently a unique attribute. The Terraform provider treats it as unique though, by throwing back the error stated above. Microsoft's own documentation on this (https://learn.microsoft.com/en-us/entra/identity/hybrid/connect/plan-connect-userprincipalname) does only specify the UPN being unique.

In the customer’s own words for their specific situation: "The code is responsible for onboarding users to HashiCorp Vault, i.e. creating entities, policies, memberships, etc. We only allow users to login to HashiCorp Vault who went through the onboarding. Therefore, it is a critical process granting access to the Secrets Management. We do not specify eligible users directly but rather their teams represented by Gitlab groups. The onboarding pipeline which runs once every hour will then fetch all members for a specified group and grant access to their team's path within Vault. The mail nickname is the only attribute that the Gitlab User and EntraID users have in common. Hence, we can only query the EntraID users by their mail nickname. Other arguments offered by the data call like `employee_ids`, `mails`, `object_ids`, or `user_principal_names` cannot be matched."

Workarounds:

Microsoft has over the years in their own products moved towards a unique `mailNickName` attribute, like for example when people utilize Active Directory. However, it is not mandatory to be unique, only the UPN has that qualifier. In the past, such as when mandating unique `mailNickName`s for Microsoft Office365, they have released tools and resources such as this documentation article (https://learn.microsoft.com/en-us/troubleshoot/entra/entra-id/user-prov-sync/proxyaddresses-attribute-populate#scenario-6-two-users-have-the-same-mailnickname-attribute) in order to change duplicate `mailNickName` attributes. This plan does not work for our customer, as they utilize this attribute in a way that they expect duplicates, and the system is working exactly as it should and this attribute is in the correct format. Their only blocker is the fact that our provider does not treat this attribute this way currently.

Desired Outcome:

The customer identified the line in the AzureAD provider code that returns the error “More than one user found with email alias”: https://github.com/hashicorp/terraform-provider-azuread/blob/4a5d291279e00f4a636873beea238e11a7644e88/internal/services/users/users_data_source.go#L293.

They simply request that the AzureAD provider provides parity with how Microsoft treats `mailNickName` as non-unique, suggesting either that the AzureAD Provider adds an attribute such as `allow_duplicates = true` to the resource, or some sort of filter criteria such as `filter = “upn=sa@mydomain.com”` in order to be able to not have to query the entire user database which is computationally expensive and possibly a PII issue.

### New or Affected Resource(s)

* azuread_XXXXX

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #0000

### PR DESCRIPTION
**Pull request by wyattfry**
## Community Note

* Please vote on this PR by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original PR to help the community and maintainers prioritize for review
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for PR followers and do not help prioritize for review

## Description

Data Source `azuread_users` - Support nonunique mail nicknames when retrieving users by their mail nicknames. Azure does not require that this property be unique, this PR updates the retrieval and validation to more closely match the Azure API.

## PR Checklist

- [x] I have followed the guidelines in our [Contributing Documentation](../blob/main/contributing/README.md).
- [x] I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change.
- [x] I have checked if my changes close any open issues. If so please include appropriate [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) below.
- [x] I have updated/added Documentation as required written in a helpful and kind way to assist users that may be unfamiliar with the resource / data source.
- [x] I have used a meaningful PR title to help maintainers and other users understand this change and help prevent duplicate work.
For example: "`resource_name_here` - description of change e.g. adding property `new_property_name_here`"

## Testing

- [x] My submission includes Test coverage as described in the [Contribution Guide](../blob/main/contributing/topics/guide-new-resource.md) and the tests pass. (if this is not possible for any reason, please include details of why you did or could not add test coverage)

image

## Change Log

Below please provide what should go into the changelog (if anything) conforming to the [Changelog Format documented here](../blob/main/contributing/topics/maintainer-changelog.md).
* `azuread_users` - * `azuread_users` - Support nonunique mail nicknames [GH-1762] [GH-1762]

This is a (please select all that apply):

- [ ] Bug Fix
- [ ] New Feature (ie adding a service, resource, or data source)
- [x] Enhancement
- [ ] Breaking Change

## Related Issue(s)
Fixes #1758

## Rollback Plan
If a change needs to be reverted, we will publish an updated version of the provider.

## Changes to Security Controls
Are there any changes to security controls (access controls, encryption, logging) in this pull request? If so, explain.

> [!NOTE]
> If this PR changes meaningfully during the course of review please update the title and description as required.

### CODE REVIEW

File: internal/services/users/users_data_source.go [hunk 1]
```diff
@@ -359,9 +358,13 @@ func usersDataSourceRead(ctx context.Context, d *pluginsdk.ResourceData, meta in
...
-	// Check that the right number of users were returned
-	if !returnAll && !ignoreMissing && len(foundUsers) != expectedCount {
-		return tf.ErrorDiagF(fmt.Errorf("expected: %d, actual: %d", expectedCount, len(foundUsers)), "Unexpected number of users returned")
+	// Check that a valid number of users was returned
+	if !returnAll && !ignoreMissing {
+		if !filteredByNonUniqueField && len(foundUsers) != expectedCount {
+			return tf.ErrorDiagF(fmt.Errorf("expected: %d, actual: %d", expectedCount, len(foundUsers)), "Unexpected number of users returned")
+		} else if filteredByNonUniqueField && len(foundUsers) < expectedCount {
+			return tf.ErrorDiagF(fmt.Errorf("expected at least %d, actual: %d", expectedCount, len(foundUsers)), "Unexpected number of users returned")
+		}
```
Comment (sreallymatt) [inline internal/services/users/users_data_source.go:367]: Since this is a data source, would it make sense to just return whatever we found if it's greater than or equal to the `expectedCount`? (or, maybe we consider deprecating `ignore_missing` and remove this check entirely for the next major version? -- cc @jackofallops)

i.e. change the previously existing condition to `if !returnAll && !ignoreMissing && len(foundUsers) < expectedCount {` rather than adding more paths?

**Review by sreallymatt — COMMENTED** [review]
Thanks @wyattfry, before I give this a more thorough review, I was just wondering about the implementation here and I've left a comment inline

**Review by sreallymatt — APPROVED** [review]
Thanks @wyattfry LGTM ✅

**Comment by sreallymatt** [comment]
image
