### PR TITLE
applications: retry on 409 after creating application

### LINKED ISSUE #1764: Create azuread_application periodically fails - unexpected status 409 (409 Conflict) with error: Error_MsaAppDoesNotExist: The corresponding MSA application does not exist.
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureAD Provider) Version

I have tried this with multiple version of terraform and multiple versions of the azuread provider - they are all unstable:

terraform: 1.11.0, 1.12.0, 1.12.2, 1.13.0-rc1, 1.13.0
azuread: 2.51.0, 3.0.0, 3.1.0, 3.5.0

### Affected Resource(s)

* `azuread_application`

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "4.0.0"
    }
    azuread = {
      source  = "hashicorp/azuread"
      version = "3.5.0"
    }
  }
  required_version = ">= 1.1.0"
}
 
provider "azurerm" {
  features {}
  resource_provider_registrations = "none"
  subscription_id                 = "XXXXXXXXXXX"
}
 
provider "azuread" {
  tenant_id     = "XXXXXXXXXXX"
  client_id     = "XXXXXXXXXXX"
  client_secret = "XXXXXXXXXXX"
}
 
data "azuread_application_published_app_ids" "well_known" {}
 
resource "azuread_application" "service-application" {
  display_name = "test"
  sign_in_audience = "AzureADandPersonalMicrosoftAccount"
 
  api {
    requested_access_token_version = 2
  } 
}
```

### Debug Output

https://gist.github.com/hkrazure/fbb09c916b38a1d7789199873318b68f

### Expected Behavior

The app registration should be created every time instead of failing some of the time.

### Actual Behavior

It fails with the following message:

│ unexpected status 409 (409 Conflict) with error: Error_MsaAppDoesNotExist:
│ The corresponding MSA application does not exist.

Apparently creating an app registration resource results in two calls from terraform - a post and a patch.

It appears that the patch request fails because azure schedules creating some resources asynchronously - but this is not awaited before the patch request is executed which results in the failure.

### Steps to Reproduce

1. Initialize terraform
2. Run terraform plan
3. Run terraform apply

1. `terraform apply`

### Important Factoids

This is an issue with sign_in_audience = "AzureADandPersonalMicrosoftAccount".

It seems to work with other sign_in_audience values.

But we need this specific one in our setup.

### References

I can see there is an issue for microsoft graph that fails with the samme message:

https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/3380

* #0000

### PR DESCRIPTION
**Pull request by brian-sqq**
## Community Note

* Please vote on this PR by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original PR to help the community and maintainers prioritize for review
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for PR followers and do not help prioritize for review

## Description

We recently started experiencing the issue reported at https://github.com/hashicorp/terraform-provider-azuread/issues/1764.  We have engaged Azure Support and I've posted their response in a [comment on the issue.](https://github.com/hashicorp/terraform-provider-azuread/issues/1764#issuecomment-3282278691).

This is my first contribution to this project, and given the simplicity of it, I am hopeful that a maintainer or regular contributor will test it.  I _am_ able to `build`, but of course the change is quite small.  Since the provider is depending on the SDK for handling other retry-able errors, I'm hopeful we can add the 409 -- admittedly, I have not interrogated the SDK.

## Changes to existing Resource / Data Source

- [x] I have added an explanation of what my changes do and why I'd like you to include them (This may be covered by linking to an issue above, but may benefit from additional explanation).
- [ ] I have written new tests for my resource or datasource changes & updated any relevant documentation.
- [x] I have successfully run tests with my changes locally. If not, please provide details on testing challenges that prevented you running the tests.
- [ ] (For changes that include a **state migration only**). I have manually tested the migration path between relevant versions of the provider.

## Testing 

- [ ] My submission includes Test coverage as described in the [Contribution Guide](../blob/main/contributing/topics/guide-new-resource.md) and the tests pass. (if this is not possible for any reason, please include details of why you did or could not add test coverage)

## Change Log

Below please provide what should go into the changelog (if anything) conforming to the [Changelog Format documented here](../blob/main/contributing/topics/maintainer-changelog.md).

* `azuread_application` - retry in case of 409 conflict, resolves [issue 1764](https://github.com/hashicorp/terraform-provider-azuread/issues/1764)

This is a (please select all that apply):

- [ ] Bug Fix
- [ ] New Feature (ie adding a service, resource, or data source)
- [x] Enhancement
- [ ] Breaking Change

## Related Issue(s)
Fixes #1764 

## Rollback Plan

If a change needs to be reverted, we will publish an updated version of the provider.

## Changes to Security Controls

Are there any changes to security controls (access controls, encryption, logging) in this pull request? If so, explain.

> [!NOTE] 
> If this PR changes meaningfully during the course of review please update the title and description as required.

### CODE REVIEW

**Comment by kornelkalnai** [comment]
We are interested in resolving this issue too.
Could someone look into this PR please? @jackofallops, @wyattfry

**Comment by brian-sqq** [comment]
We have built and published this to our Terraform Cloud private repository, and used it several times with success.  We will continue to use our fork until this is merged, but ask that a maintainer please review and merge this so we can get back to the main-line.

File: internal/services/applications/application_resource.go [hunk 1]
```diff
@@ -1241,6 +1241,7 @@ func applicationResourceCreate(ctx context.Context, d *pluginsdk.ResourceData, m
 
 	// Attempt to patch the newly created application and set the display name, which will tell us whether it exists yet, then set it back to the desired value.
 	// The SDK handles retries for us here in the event of 404, 429 or 5xx, then returns after giving up.
+	// Our retry function also retries on 409.
```
Comment (jackofallops) [inline internal/services/applications/application_resource.go]:
```suggestion
	// Due to an unusual implementation on this service, the retry function also retries on 409. See https://github.com/hashicorp/terraform-provider-azuread/issues/1764#issuecomment-3282278691 for more information.
```

File: internal/services/applications/applications.go [hunk 2]
```diff
@@ -27,7 +27,7 @@ import (
 
 func applicationUpdateRetryFunc() client.RequestRetryFunc {
 	return func(resp *http.Response, o *odata.OData) (bool, error) {
-		if response.WasNotFound(resp) {
+		if response.WasNotFound(resp) || response.WasConflict(resp) {
```
Comment (jackofallops) [inline internal/services/applications/applications.go]: Since this is used in several calls, we should include a comment here too @copilot 
```suggestion
		// inconsistent state on this resource can result in a 409 Conflict being returned, in this exception case we retry as per the service design, see  https://github.com/hashicorp/terraform-provider-azuread/issues/1764#issuecomment-3282278691 for more information.
		if response.WasNotFound(resp) || response.WasConflict(resp) {
```

**Review by jackofallops — CHANGES_REQUESTED** [review]
Hi @brian-sqq - Thanks for this. Since it's something of an anti-pattern, can you take a look at including the extra context in the comment suggestions below to assist future contributions for this resoruce?

Thanks

**Comment by jackofallops** [comment]
Tests passing 👍 
image

**Review by jackofallops — APPROVED** [review]
Hi @brian-sqq - Thanks for the changes, this LGTM now 👍
